services:
  react_app:
    container_name: React_App
    build: 
      context: .
      dockerfile: docker/Dockerfile   
    ports:
      - 5173:5173
    volumes:
      - ./react_app:/usr/src/app/react_app
      - /usr/src/app/react_app/node_modules
    networks:
      - react_learn
        
networks:
  react_learn:
    driver: bridge
